
  - repo: https://github.com/iterative/dvc
    # use a specific version (e.g. 1.8.1) instead of master if you don't want
    # to use the upstream version
    rev: master
    hooks:
    - id: dvc-pre-commit
      language_version: python3
      stages:
        - commit
    - id: dvc-pre-push
      # use s3/gs/etc instead of all to only install specific cloud support
      additional_dependencies: ['.[gs]']
      language_version: python3
      stages:
        - push
    - always_run: true
      id: dvc-post-checkout
      language_version: python3
      stages:
        - post-checkout
