name: Run checks
on:
  pull_request:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      PYTHONPATH: "."
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.16.1'

      - name: "Run pre-commits"
        uses: pre-commit/action@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dependencies"
        run: ./ci/install_deps.sh

      - name: "Test with pytest"
        run: ./ci/run_checks.sh
